name: Playwright Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

env:
  # override value from .env.testnet used in CI
  NEXT_PUBLIC_SITE_URL: http://127.0.0.1:3000

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Install packages
        run: yarn install
      - name: Install Playwright browsers
        run: yarn playwright install --with-deps
      - name: Set up testnet environment
        run: cp apps/dapp/.env.testnet apps/dapp/.env.local
      - name: Build dApp
        run: yarn dapp build
      - name: Run Playwright tests
        run: yarn test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/dapp/playwright-report/
          retention-days: 30
